default: &default
  adapter: postgresql
  timeout: 5000
  host: localhost
  encoding: unicode
  username: postgres
  password: 
  pool: 5

development:
  <<: *default
  database: calendar_app_dev

test:
  <<: *default
  database: calendar_app_test

